CLASS zcl_119017_demo_0101 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_119017_DEMO_0101 IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.
    out->write('Hello ABAP in Cloud!').
  ENDMETHOD.
ENDCLASS.
